# These are supported funding model platforms
github: nk10nikhil
patreon: nk10nikhil
open_collective: nk10nikhil-portfolio
ko_fi: nk10nikhil
tidelift: nk10nikhil-portfolio
community_bridge: nk10nikhil-portfolio
liberapay: nk10nikhil
issuehunt: nk10nikhil
lfx_crowdfunding: nk10nikhil-portfolio
polar: nk10nikhil
buy_me_a_coffee: nk10nikhil
custom: ['https://paypal.me/nk10nikhil', 'https://www.buymeacoffee.com/nk10nikhil', 'https://www.patreon.com/nk10nikhil', 'https://ko-fi.com/nk10nikhil']